# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibition",
            name="season_id",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="season_id",
        ),
    ]
