# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20170629_0946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
