# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20170630_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="association_other",
            field=models.CharField(
                blank=True,
                help_text='Only supply if the association is "Other".',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="divisions",
            field=models.CharField(
                blank=True,
                help_text="Divisions tournament is for. * Optional",
                max_length=4000,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateField(
                help_text="Please supply the start date of the tournament"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="URL to webpage about tournament. * Optional but recommended to supply",
                max_length=4000,
            ),
        ),
    ]
