# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20170706_0851"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibition",
            name="end_date",
        ),
        migrations.AddField(
            model_name="exhibition",
            name="other_team_association",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Association",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exhibition",
            name="other_team_association_other",
            field=models.CharField(
                blank=True,
                help_text='Only supply if the association is "Other".',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
