# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20170828_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="other_team_association",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Association",
                verbose_name="Other Team Association",
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="other_team_association_other",
            field=models.CharField(
                blank=True,
                help_text='If you have selected "Other" for the Other Team Association, who is it?',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="start_date",
            field=models.DateTimeField(verbose_name="Start Date and Time"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="association",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Association",
                verbose_name="Host Association",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="association_other",
            field=models.CharField(
                blank=True,
                help_text='If you have selected "Other" for the Host Association, who is it?',
                max_length=255,
                verbose_name="Host Association Other",
            ),
        ),
    ]
