# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_auto_20170828_1011"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="exhibition",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="End Date and Time"
            ),
        ),
        migrations.AddField(
            model_name="exhibition",
            name="referee_requirements",
            field=models.CharField(
                choices=[
                    ("2 Refs", "2 Refs"),
                    ("1 Ref / 2 Linesmen", "1 Ref / 2 Linesmen"),
                    ("2 Refs / 2 Linesmen", "2 Refs / 2 Linesmen"),
                ],
                default="No Referee Needed",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="arena",
            field=models.CharField(
                blank=True,
                help_text="Ensure you include the pad/rink number as well!",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="exhibition",
            name="rink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Rink",
            ),
        ),
    ]
