# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_auto_20170907_1933"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibition",
            name="requires_referee",
        ),
        migrations.AddField(
            model_name="exhibition",
            name="timekeeper_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="referee_requirements",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2 Refs", "2 Refs"),
                    ("1 Ref / 2 Linesmen", "1 Ref / 2 Linesmen"),
                    ("2 Refs / 2 Linesmen", "2 Refs / 2 Linesmen"),
                ],
                help_text="* Timekeeper must be knowledgeable on how to properly fill out a game sheet",
                max_length=255,
            ),
        ),
    ]
