# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_auto_20170907_1955"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="timekeeper_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="referee_requirements",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2 Refs", "2 Refs"),
                    ("1 Ref / 2 Linesmen", "1 Ref / 2 Linesmen"),
                    ("2 Refs / 2 Linesmen", "2 Refs / 2 Linesmen"),
                ],
                max_length=255,
            ),
        ),
    ]
