# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_auto_20170907_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="required_referee_or_timekeeper",
            field=models.BooleanField(default=False),
        ),
    ]
