# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_auto_20170907_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="destination",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="other_team_association_other",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Other Team Association "Other"',
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="association_other",
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Host Association "Other"'
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateField(verbose_name="Tournament Start Date"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="website",
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
