# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_auto_20170908_1247"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rink",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="exhibition",
            name="referee_timekeeper_request_sent_to_office",
            field=models.BooleanField(default=False),
        ),
    ]
