# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_remove_exhibition_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="cell_phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exhibition",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="End Date and Time"
            ),
        ),
    ]
