# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_auto_20171013_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="exhibition_is_in_ohf",
            field=models.BooleanField(default=False),
        ),
    ]
