# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_association_exhibition_is_in_ohf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="exhibition_is_in_ohf",
            field=models.BooleanField(
                default=False,
                help_text="Setting applies to Exhibitions only, is this association within the OHF?",
            ),
        ),
    ]
