# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_auto_20171122_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="rink",
            field=models.ForeignKey(
                default=19,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.Rink",
            ),
            preserve_default=False,
        ),
    ]
