# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_auto_20171122_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="cell_phone",
            field=models.CharField(
                blank=True,
                help_text="This is the phone number you will be contacted at if there is a problem.",
                max_length=255,
            ),
        ),
    ]
