# Generated by Django 2.1.3 on 2018-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_auto_20180907_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="timekeeper_needed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
