[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
extend_skip = "temp.py"

[tool.coverage.run]
omit = [
    "manage.py", 
    ".venv/*", 
    "**/tests.py",
    "*migrations*",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sportsnet.settings"
python_files = "tests.py test_*.py *_tests.py"
