# Generated by Django 4.0.3 on 2022-03-15 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("qualifications", "0002_qualification_qualificationrule"),
        ("core", "0003_package_package_package_name_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_sk_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The old primary id for the entry",
                        null=True,
                        unique=True,
                    ),
                ),
                ("inserted", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("note_for_person", models.TextField(blank=True)),
                ("note_for_internal", models.TextField(blank=True)),
                ("season_year", models.IntegerField()),
                ("DocCatg", models.TextField(blank=True, max_length=255)),
                ("DocType", models.TextField(blank=True, max_length=255)),
                ("DocNote", models.TextField(blank=True, max_length=255)),
                ("DocRef", models.TextField(blank=True, max_length=255)),
                ("attained", models.BooleanField()),
                ("passed", models.BooleanField()),
                ("certified", models.BooleanField()),
                ("certified_date", models.DateField(blank=True, null=True)),
                ("FacilityCode", models.TextField(blank=True, max_length=255)),
                ("FacilityAddress", models.TextField(blank=True, max_length=255)),
                ("FacilityCity", models.TextField(blank=True, max_length=255)),
                ("FacilityProvince", models.TextField(blank=True, max_length=255)),
                ("FacilityPostal", models.TextField(blank=True, max_length=255)),
                (
                    "document_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="qualifications.documentcategory",
                    ),
                ),
                (
                    "document_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="qualifications.documentlevel",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="qualifications.documenttype",
                    ),
                ),
                (
                    "inserted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_inserted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
