# Generated by Django 4.0.3 on 2022-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_memberdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionoverrides",
            name="team_can_access",
            field=models.BooleanField(default=True),
        ),
    ]
