# Generated by Django 4.0.3 on 2022-03-10 17:19

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_season_season_name_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="league",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.expressions.F("season"),
                name="season_league_name_unique",
            ),
        ),
    ]
