# Generated by Django 4.0.3 on 2022-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_league_season_league_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="assign_first_slot_as_goalie",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="division",
            name="player_rating_factor",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="subdivision",
            name="default_number_of_teams",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="subdivision",
            name="inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subdivision",
            name="player_rating_factor",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
