# Generated by Django 4.0.3 on 2022-03-10 22:05

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_division_assign_first_slot_as_goalie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subdivision",
            options={"ordering": ["weight"]},
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.expressions.F("season"),
                django.db.models.expressions.F("league"),
                name="division_season_league_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="subdivision",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.expressions.F("season"),
                django.db.models.expressions.F("league"),
                django.db.models.expressions.F("division"),
                name="subdivision_season_league_division_name_unique",
            ),
        ),
    ]
