# Generated by Django 4.0.3 on 2022-03-11 16:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_subdivision_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models._UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        help_text="Typically the app it belongs to i.e. games",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name that corresponds to the value stored i.e. username",
                        max_length=255,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the computer this setting is specific to.",
                        max_length=255,
                    ),
                ),
                ("value", models.TextField(blank=True)),
                ("inserted", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["app", "name", "hostname"],
                "abstract": False,
                "unique_together": {("app", "name", "hostname")},
            },
        ),
    ]
