# Generated by Django 4.0.3 on 2022-03-11 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_user_options_user_inserted_by_user_old_sk_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inserted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
