# Generated by Django 4.0.3 on 2022-03-13 17:38

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teamstatusreason",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.expressions.F("status"),
                name="teamstatusreason_name_status_uniqueness",
            ),
        ),
    ]
