# Generated by Django 4.0.3 on 2022-03-14 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_player_playerstatus_playertype_playerstatusreason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playertype",
            name="change_causes_player_flag_on_team_to_enable",
        ),
        migrations.AddField(
            model_name="playerstatus",
            name="change_causes_player_flag_on_team_to_enable",
            field=models.BooleanField(
                default=True,
                help_text="Does changing a Player record assigned with this PlayerType cause the team.player_has_changed_flag to be True?",
                verbose_name="Change causes team.player_has_changed_flag set to True",
            ),
        ),
        migrations.AlterField(
            model_name="playerstatuslog",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_log",
                to="team.player",
            ),
        ),
    ]
