# Generated by Django 4.0.3 on 2022-03-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_staff_inserted_by_staff_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftype",
            name="change_causes_staff_flag_on_team_to_enable",
            field=models.BooleanField(
                default=True,
                help_text="Does changing a Staff record assigned with this StaffType cause the team.staff_has_changed_flag to be True?",
                verbose_name="Change causes team.staff_has_changed_flag set to True",
            ),
        ),
        migrations.AlterField(
            model_name="stafftype",
            name="web_access",
            field=models.BooleanField(
                default=False,
                help_text="Can a Staff record assigned with this StaffType be allowed to login?",
            ),
        ),
    ]
