# Generated by Django 4.0.3 on 2022-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_team_approval_required_team_registration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftype",
            name="team_can_access",
            field=models.BooleanField(default=True),
        ),
    ]
