# Generated by Django 4.0.3 on 2022-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_remove_team_status_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="old_teamseason_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
