# Generated by Django 4.0.3 on 2022-03-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0008_team_old_teamseason_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffstatus",
            options={
                "ordering": ["weight"],
                "verbose_name": "Staff Status",
                "verbose_name_plural": "Staff Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="stafftype",
            options={
                "ordering": ["weight"],
                "verbose_name": "Staff Type",
                "verbose_name_plural": "Staff Types",
            },
        ),
    ]
